### ISSUE TITLE
TODO: Expand functionality of PR cleanup procedure 

### ISSUE THREAD

**Issue by Neves-P** [Neves-P/eessi-bot-software-layer#1]
With https://github.com/EESSI/eessi-bot-software-layer/pull/271 merged, there are a few follow-up tasks to have all the necessary functionality. At the moment, the merged code will move (and copy if not possible, as a fallback) the directories of PRs that have been merged. What still needs to be done:
- [ ] Write a script to remove directories older than a set limit.
- [ ] Setup cronjob to run said script
- [ ] Tweak move process to correctly handle symlinks
- [ ] Let existing code move directories for closed PRs, not just merged ones. Ensure closing regular issues (as opposed to PRs) doesn't create problems.
